all:
	make black
	make run
run:
	python test_camera.py
	python test_camera_up.py
	python test_camera_zoom.py
	python test_clip_box.py
	python test_multi_renderers.py
	python test_shrink.py
	python test_widget_box.py
black:
	black -l 40 .
