# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - libgl1-mesa-dev
    - xvfb
  commands:
    - cd docs && make revealjs && mv _build/revealjs _build/html

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt
