all:
	make black
	make run
run:
	python test_geometric_objects.py
	python test_pyramid.py
	python test_extrude_rotate.py
	python test_plot_over_line1.py
	python test_plot_over_line2.py
	python test_plot_over_circular_arc1.py
	python test_plot_over_circular_arc2.py
black:
	black -l 50 .
